
import javax.swing.JOptionPane;

/**
 *
 * @author Fernando Hernandez
 */
public class BlastUI extends javax.swing.JFrame {

    private static final String APP_NAME = "BLAST UI";
    private static final String APP_Version = "Version 1.0";
    private static final int TYPE_DNA = 0;
    private static final int TYPE_RNA = 1;
    private static final int TYPE_Protein = 2;
    private static final double SEQ_TRESHOLD = .85;

    /**
     * Creates new form BlastUI. This is the main GUI of the program
     */
    public BlastUI() {
        super();
        initComponents();
    }

    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new BlastUI().setVisible(true);
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        program_select = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        seqArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        run_seq = new javax.swing.JButton();
        program_label = new javax.swing.JLabel();
        db_label = new javax.swing.JLabel();
        evalue_label = new javax.swing.JLabel();
        status_label = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        blastN_button = new javax.swing.JRadioButton();
        blastx_button = new javax.swing.JRadioButton();
        tblastx_button = new javax.swing.JRadioButton();
        blastp_button = new javax.swing.JRadioButton();
        tblastn_button = new javax.swing.JRadioButton();
        clear_button = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BLAST UI Version 1.1");
        setResizable(false);

        seqArea.setColumns(20);
        seqArea.setRows(5);
        seqArea.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                seqAreaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                seqAreaFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(seqArea);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setText("Sequence");

        run_seq.setLabel("Format Sequence");
        run_seq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                run_seqActionPerformed(evt);
            }
        });

        program_label.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        program_label.setText("Program:");

        db_label.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        db_label.setText("Database:");

        evalue_label.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        evalue_label.setText("E-value:");

        status_label.setText("Status: Ready");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "nr", "refseq" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { ".01", ".001", ".0001", ".00001" }));

        program_select.add(blastN_button);
        blastN_button.setText("BlastN");
        blastN_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blastN_buttonActionPerformed(evt);
            }
        });

        program_select.add(blastx_button);
        blastx_button.setText("BlastX");

        program_select.add(tblastx_button);
        tblastx_button.setText("TBlastX");

        program_select.add(blastp_button);
        blastp_button.setText("BlastP");

        program_select.add(tblastn_button);
        tblastn_button.setText("TBlastN");

        clear_button.setText("Clear");
        clear_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_buttonActionPerformed(evt);
            }
        });

        fileMenu.setMnemonic('f');
        fileMenu.setText("Sequence Form");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        jMenu1.setText("Blast Result");
        menuBar.add(jMenu1);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(evalue_label)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(db_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(program_label))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(blastN_button)
                                        .addGap(18, 18, 18)
                                        .addComponent(blastx_button)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tblastx_button)
                                        .addGap(18, 18, 18)
                                        .addComponent(blastp_button)
                                        .addGap(18, 18, 18)
                                        .addComponent(tblastn_button))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(86, 86, 86)
                                        .addComponent(run_seq, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 73, Short.MAX_VALUE)))
                        .addGap(111, 111, 111))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(status_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clear_button)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(clear_button))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(run_seq)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(program_label)
                            .addComponent(blastN_button)
                            .addComponent(blastx_button)
                            .addComponent(tblastx_button)
                            .addComponent(blastp_button)
                            .addComponent(tblastn_button))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(db_label)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(evalue_label)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(status_label)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void run_seqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_run_seqActionPerformed
      //Grab the text from the input area
        
        
          String seqText = seqArea.getText();
        int index = seqText.indexOf(">");

        //if the first character isnt a >, then the string isnt in fasta
        boolean isFastaFormat = index != -1;
        int count =0;
        String header = "";
        int seqLength = 0;
        String sequence = "";
        String fastaSeq = "";

        //is it in fasta format?
        if (isFastaFormat) {
            count++;
            //if it is in fasta format, just grab the sequence
            int returnIndex = seqText.indexOf("\n");
            //
            header = seqText.substring(0, returnIndex);
            fastaSeq = seqText.substring(returnIndex + 1, seqText.length()).replaceAll("\\s", "").toLowerCase();
            fastaSeq = seqText;
        } else {
            seqText = seqText.replaceAll("\\s", "");
            fastaSeq = seqText.toLowerCase();
            header = "> Sequence " + count;
            seqLength = seqText.length();
        }
        if (!isFastaFormat) {
            fastaSeq = header + " | " + seqLength + "\n" + fastaSeq;
        }
        seqArea.setText(fastaSeq);
        /*
        String seqText = seqArea.getText();
        
        //convert the input into FASTA
        String header = null;
        int seqLength = 0;
        String sequence = "";
        String fastaSeq = "";
        int count = 0;

        //format our inputs. First, it removes all white spaces.
        //then, it changes everything to lower case.
        //Then it adds the header to the sequence
        // finally, it adds the sequence length to the header
        seqText = seqText.replaceAll("\\s", "");
        sequence = seqText.toLowerCase();
        header = "> Sequence " + count;
        seqLength = seqText.length();
        fastaSeq = header + " | " + seqLength + "\n" + sequence;

        //paste the fasta sequence into our textbox

        seqArea.setText(fastaSeq);
         */
      
    }//GEN-LAST:event_run_seqActionPerformed

    private void blastN_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blastN_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blastN_buttonActionPerformed

    private void seqAreaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_seqAreaFocusGained

  
    }//GEN-LAST:event_seqAreaFocusGained

    private void is
    private void seqAreaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_seqAreaFocusLost
        //grab the text from the inputbox
        String seqText = seqArea.getText();
        int index = seqText.indexOf(">");

        //if the first character isnt a >, then the string isnt in fasta
        boolean isFastaFormat = index != -1;
        int count =0;
        String header = "";
        int seqLength = 0;
        String sequence = "";
        String fastaSeq = "";

        //is it in fasta format?
        if (isFastaFormat) {
            count++;
            //if it is in fasta format, just grab the sequence
            int returnIndex = seqText.indexOf("\n");
            //
            header = seqText.substring(0, returnIndex);
            fastaSeq = seqText.substring(returnIndex + 1, seqText.length()).replaceAll("\\s", "").toLowerCase();
            fastaSeq = seqText;
        } else {
            seqText = seqText.replaceAll("\\s", "");
            fastaSeq = seqText.toLowerCase();
            header = "> Sequence " + count;
            seqLength = seqText.length();
        }
        if (!isFastaFormat) {
            fastaSeq = header + " | " + seqLength + "\n" + fastaSeq;
        }
        seqArea.setText(fastaSeq);

    }//GEN-LAST:event_seqAreaFocusLost

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        JOptionPane.showMessageDialog(BlastUI.this, APP_NAME + " " + APP_Version,
                "About " + APP_NAME, JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void clear_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_buttonActionPerformed
        seqArea.setText("");
    }//GEN-LAST:event_clear_buttonActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JRadioButton blastN_button;
    private javax.swing.JRadioButton blastp_button;
    private javax.swing.JRadioButton blastx_button;
    private javax.swing.JButton clear_button;
    private javax.swing.JLabel db_label;
    private javax.swing.JLabel evalue_label;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JLabel program_label;
    private javax.swing.ButtonGroup program_select;
    private javax.swing.JButton run_seq;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JTextArea seqArea;
    private javax.swing.JLabel status_label;
    private javax.swing.JRadioButton tblastn_button;
    private javax.swing.JRadioButton tblastx_button;
    // End of variables declaration//GEN-END:variables
}
